HAI 1.2
  I HAS A NAME
  VISIBLE "WHAT IS UR NAEM"
  GIMMEH NAME
  I HAS A ACTION
  VISIBLE SMOOSH "HAI " NAME ""
  GIMMEH ACTION
  I HAS A ASK
  VISIBLE SMOOSH "SO WHAT U WANT DO " NAME ""
  GIMMEH ASK
  I HAS A PLA
  VISIBLE SMOOSH "OK LETS "ASK" A GAME"
  GIMMEH PLA
KTHXBYE
